# To use this file, run `docker-compose up`.
version: '3.4'

x-backend-config: &backend
  build:
    context: "."
    dockerfile: "./scripts/docker/Dockerfile.backend"

services:
  # Main application
  backend:
    <<: *backend
    volumes:
      - .:/usr/src/app

  # Migration service
  migration:
    <<: *backend
    volumes:
      - .:/usr/src/app

  frontend:
    build:
      context: "."
      dockerfile: "./scripts/docker/Dockerfile.frontend_development"
    volumes:
      - ".:/usr/src/app"
    ports:
      - 3000:3000 
    labels:
      - traefik.http.routers.frontend.rule=(Host(`localhost`) || Host(`${TM_APP_BASE_DOMAIN:-127.0.0.1}`))
      - traefik.http.services.frontend.loadbalancer.server.port=3000