version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
      - ./logs/:/logs/
    ports:
      - 80:80
    entrypoint: uvicorn backend.main:api --host 0.0.0.0 --port 80 --reload

  postgresql:
    image: postgis/postgis:14-3.3
    container_name: postgresql
    restart: always
    env_file: ${ENV_FILE:-tasking-manager.env}
    ports:
      - "5436:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
