version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  database-snapshot:
    parameters:
      stack_name:
        description: "CloudFormation stack name"
        type: string
    working_directory: /home/circleci/app
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "database-snapshot"
          session-duration: "1800"
      - run:
          name: Get RDS Instance ID
          command: |
            RDS_ID=$(aws rds describe-db-instances --query 'DBInstances[?contains(TagList[].Key, `aws:cloudformation:stack-name`) && contains(TagList[].Value, `tasking-manager-<< parameters.stack_name >>'`)].[DBInstanceIdentifier]' --output text)
            echo "export RDS_ID=$RDS_ID" >> $BASH_ENV
      - run:
          name: Backup the database
          no_output_timeout: 15m
          command: |
            TIME_NOW=$(date --utc '+%s')
            aws rds create-db-snapshot \
                        --db-snapshot-identifier << parameters.stack_name >>-${RDS_ID}-${TIME_NOW} \
                        --db-instance-identifier ${RDS_ID} \
                        --tags Key=stack_name,Value=<< parameters.stack_name >> Key=unix_utc_epoch,Value=$(date --utc '+%s')
            aws rds wait db-snapshot-completed \
                        --db-snapshot-identifier << parameters.stack_name >>-${RDS_ID}-${TIME_NOW} \
                        --db-instance-identifier ${RDS_ID}
            if [[ $? -eq 255 ]]; then
              echo "Production snapshot creation failed. Exiting with exit-code 125"
              exit 125
            fi

  build:
    # TODO: Split me into separate Frontend and Backend builds
    working_directory: /home/circleci/app
    resource_class: large
    docker:
      - image: cimg/python:3.7-node
        environment:
          SQLALCHEMY_DATABASE_URI: postgresql://taskingmanager@localhost/test_tm
      - image: cimg/postgres:14.7-postgis
        environment:
          POSTGRES_USER: taskingmanager
          POSTGRES_DB: test_tm
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install modules
          command: |
            sudo apt-get update
            sudo apt-get install -y libgeos-dev # Required for shapely
            sudo yarn global add @mapbox/cfn-config @mapbox/cloudfriend
            pip install awscli --upgrade
      - run:
          name: Configure Postgresql Test database
          command: |
            sudo apt-get install postgresql-client
            psql -h localhost -U $POSTGRES_USER test_$POSTGRES_DB -c "CREATE EXTENSION postgis;"
      - run:
          name: Set folder permissions
          command: |
            chown -R circleci:circleci ${CIRCLE_WORKING_DIRECTORY}
            chmod -R 755 ${CIRCLE_WORKING_DIRECTORY}
      - restore_cache:
          keys:
            - node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install requirements
          command: |
            # Install NPM packages and build frontend
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend
            yarn
            cd ${CIRCLE_WORKING_DIRECTORY}
            # Install Python dependencies
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run backend code checks
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/lint
            black --check manage.py backend tests migrations
            flake8 manage.py backend tests migrations
      - run:
          name: Run frontend tests
          command: |
            # JS Unit Tests
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend
            CI=true yarn test -w 1
            CI=true GENERATE_SOURCEMAP=false yarn build
      - run:
          name: Run backend tests
          command: |
            # Run Python tests
            cd ${CIRCLE_WORKING_DIRECTORY}
            mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results
            find ./tests/backend -name "test*.py" -exec chmod -x {} \;
            nosetests ./tests/backend --with-xunit \
              --xunit-file ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/unitresults.xml \
              --with-coverage --cover-erase --cover-package=./backend
            coverage xml -o ${CIRCLE_WORKING_DIRECTORY}/tests/backend/results/coverage.xml
      - store_test_results:
          path: tests/backend/results
      - store_artifacts:
          path: tests/backend/results
      - save_cache:
          key: node-{{ .Environment.CACHEVERSION }}-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
            - env

  backend_deploy:
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
      gitsha:
        description: "The 40 char hash of the git commit"
        type: string
    working_directory: /home/circleci/tasking-manager
    resource_class: medium
    docker:
      - image: cimg/python:3.7-node
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "backend-deploy"
          session-duration: "2700"
      - run:
          name: Install modules
          command: |
            sudo apt-get update
            sudo apt-get install -y libgeos-dev jq # Required for shapely
            sudo yarn global add @mapbox/cfn-config @mapbox/cloudfriend
            pip install awscli --upgrade

      - run:
          name: Download config file
          command: |
            export GITSHA=<< parameters.gitsha >>
            aws s3 cp s3://hot-cfn-config/tasking-manager/tasking-manager-<< parameters.stack_name >>-${AWS_REGION}.cfn.json - | jq -c --arg GITSHA "$GITSHA" '.GitSha = $GITSHA' > $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json
      - deploy:
          name: Deploy to << parameters.stack_name >>
          command: |
            export NODE_PATH=/usr/local/share/.config/yarn/global/node_modules/
            validate-template $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js
            export JSON_CONFIG="$(cat $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json)"
            cfn-config update << parameters.stack_name >> $CIRCLE_WORKING_DIRECTORY/scripts/aws/cloudformation/tasking-manager.template.js -f -c hot-cfn-config -t hot-cfn-config -r $AWS_REGION -p "$JSON_CONFIG"

  frontend_deploy:
    working_directory: /home/circleci/tasking-manager
    resource_class: large
    docker:
      - image: cimg/python:3.7-node
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role-arn: "arn:aws:iam::$ORG_AWS_ACCOUNT_ID:role/CircleCI-OIDC-Connect"
          profile-name: "OIDC-Profile"
          role-session-name: "frontend-deploy"
          session-duration: "1800"
      - run:
          name: Deploy Frontend to S3
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/frontend/
            export TM_ENVIRONMENT=<< parameters.stack_name >>
            yarn
            CI=true GENERATE_SOURCEMAP=false yarn build
            aws s3 sync build/ s3://tasking-manager-<< parameters.stack_name >>-react-app --delete --cache-control max-age=31536000
            aws s3 cp s3://tasking-manager-<< parameters.stack_name >>-react-app s3://tasking-manager-<< parameters.stack_name >>-react-app --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control no-cache --content-type text/html
            export DISTRIBUTION_ID=$(aws cloudformation list-exports --output=text --query "Exports[?Name=='tasking-manager-<< parameters.stack_name >>-cloudfront-id-${AWS_REGION}'].Value")
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  production-all:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-snapshot:
          name: Backup production database
          stack_name: "tm4-production"
      - build
      - backend_deploy:
          name: backend-production
          stack_name: "tm4-production"
          requires:
            - build
            - database_snapshot
          gitsha: $CIRCLE_SHA1
          context:
            - org-global
            - tasking-manager-tm4-production
      - frontend_deploy:
          name: frontend-production
          stack_name: "tm4-production"
          requires:
            - build
          context:
            - org-global
            - tasking-manager-tm4-production

  production-frontend:
    when:
      and:
        - equal: [ deployment/hot-tasking-manager-frontend, << pipeline.git.branch >> ]
    jobs:
      - build
      - frontend_deploy:
          stack_name: "tm4-production"

  staging-all:
    when:
      or:
        - equal: [ develop, << pipeline.git.branch >> ]
        - equal: [ staging-test, << pipeline.git.branch >> ]
    jobs:
      - database-snapshot:
          name: Backup staging database
          stack_name: "staging"
      - build
      - backend_deploy:
          stack_name: "staging"
          gitsha: $CIRCLECI_SHA1
      - frontend_deploy:
          stack_name: "staging"

  teachosm-all:
    when:
      and:
        - equal: [ deployment/teachosm-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-snapshot:
          name: Backup TeachOSM database
          stack_name: "teachosm"
      - build
      - backend_deploy:
          name: Deploy TeachOSM Backend
          stack_name: "teachosm"
          requires:
            - build
          gitsha: $CIRCLECI_SHA1
          context: tasking-manager-teachosm
      - frontend_deploy:
          name: Deploy TeachOSM Frontend
          stack_name: "teachosm"
          requires:
            - build
          context: tasking-manager-teachosm

  tm-assisted-all:
    when:
      and:
        - equal: [ deployment/assisted-tasking-manager, << pipeline.git.branch >> ]
    jobs:
      - database-snapshot:
          name: Backup TM Assisted database
          stack_name: "assisted"
      - build
      - backend_deploy:
          name: Deploy TM Assisted Backend
          stack_name: "assisted"
          requires:
            - build
          gitsha: $CIRCLECI_SHA1
          context: tasking-manager-assisted
      - frontend_deploy:
          name: Deploy TM Assisted Frontend
          stack_name: "assisted"
          requires:
            - build
          context: tasking-manager-assisted

  development-staging-all:
    when:
      or:
        - equal: [ develop, << pipeline.git.branch >> ]
        - equal: [ staging-test, << pipeline.git.branch >> ]
    jobs:
      - build:
          context: tasking-manager-testing
      - backend_deploy:
          name: Deploy development/staging backend
          stack_name: "staging"
          requires:
            - build
          gitsha: $CIRCLE_SHA1
          context:
            - org-global
            - tasking-manager-staging
      - frontend_deploy:
          name: Deploy development/staging frontend
          stack_name: "staging"
          requires:
            - build
          context:
            - org-global
            - tasking-manager-staging

  build-only-all:
    when:
      not:
        matches:
          pattern: "^deployment/.*"
          value: << pipeline.git.branch >>
    jobs:
      - build:
          context: tasking-manager-testing

