version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build-sucess:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: 
          name: Running sleep command
          command: |
            echo "Waiting for 5 seconds..."
            sleep 5
            echo "Done waiting for 5..."

  build-fail:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: 
          name: Running sleep command
          command: |
            echo "Causing this to fail..."
            cat non-existing-file
    
  
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-sucess
      - build-fail

notify:
  webhooks:
    - url: https://api.opsgenie.com/v1/json/circleci?apiKey=${OPSGENIE_API}
